### ISSUE TITLE
stop fishing suddenly

### ISSUE THREAD

**Issue by RanggaGibran** [thejoabo/virtualfisher-bot#10]
i like the previous version before updating window size detection. it works, but when i fish bout 3-5 it suddenly stop.

**Comment by thejoabo** [comment]
Hello @RanggaGibran,
The window size detection is compartmentalized in the menu session so it shouldn't influence in any way the message flow (which is handled in another thread). **I would need some more information so I can properly identify your issue.** So please provide a detailed description of your problem. Any message appears when you exit the program ? Anything shows up on the top informing some unusual behavior ? Your config is correctly set up (you can reply with a screenshot of it, if you want) ?

The old version is still available (as any of older versions) on the commit history. You can get the v1.0.0 (the one you are referring to) here: https://github.com/thejoabo/virtualfisher-bot/blob/6f817653929f774c631f89c0461ca6ffe18f5a6c/autofishbot.py

[I just tested the current version on a fresh Windows 10 machine](https://prnt.sc/lipwWLS752B1) (following the [Installation and Usage](https://github.com/thejoabo/virtualfisher-bot#installation-and-usage) steps) and works perfectly. So unless you provide more info I can't figure out whats wrong.

**Comment by RanggaGibran** [comment]
![image](https://user-images.githubusercontent.com/101553767/180599507-a21df676-bb2b-4b52-b9bf-56333eaa91d9.png)

my cooldown 2.9
in my autofish.config is 3.5

**Comment by thejoabo** [comment]
Hello @RanggaGibran,

I did some more testing and I think I didn't added the proper handling method of cooldown related messages (it should break and send another '%f'), since its not breaking (and just passing) it halts the bot indefinitely. I'll fix this on the next update. Thanks for reporting it. If the problem persists after the next update feel free to open this issue again.
