### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by yudhistiraindyka** [thejoabo/virtualfisher-bot#24]
Hello @thejoabo, I just tried the latest release (1.2.0) and encountered this error:
![image](https://user-images.githubusercontent.com/33085123/182129519-846bdc41-e888-4d2a-b977-e5cd97858125.png)

The error suggests unsupported data type in ConfigManager.py line 87, I tried fiddling with it and the program works only if I set the data type to either only integers or floats, but not both.

I changed this:
![image](https://user-images.githubusercontent.com/33085123/182129174-f5d8705a-5343-4350-93c7-9a34bdfee59a.png)

To this:
![image](https://user-images.githubusercontent.com/33085123/182129483-a98130b2-a995-426d-8dff-9f632a3e48c7.png)

and it works
![image](https://user-images.githubusercontent.com/33085123/182129816-29ad8fe2-0a69-41cb-92d5-72d8acc56082.png)

I don't know if it's intended or not but for the meantime I'll use the aforementioned workaround, thank you so much!

**Comment by thejoabo** [comment]
This was intentional (but completly irrelevant), the " \| " operator means "OR", since python is not a typed language I just define the types for organization purposes. Anyways, this really shouldn't raise any errors, **which version of python are you running** ?

**Comment by yudhistiraindyka** [comment]
I'm using python 3.8.2

**Comment by thejoabo** [comment]
Oh, that might be why. I'm building it with Python 3.10.4 and it doesn't seem to raise anything about that. I'll keep support for older versions tho.
