### ISSUE TITLE
I Think You Should Migrate using DISCORD S.C.U.M

### ISSUE THREAD

**Issue by gabeaventh** [thejoabo/virtualfisher-bot#29]
hello, I'm very impressed by your idea of making this UserBot

but the thing is they disable the typed commands, and only allowed using SlashCommands (as shown by the image)
![image](https://user-images.githubusercontent.com/7519522/187688878-a8618b79-622c-45ab-960c-1140bd2b92fd.png)

I'd suggest you move it to https://github.com/Merubokkusu/Discord-S.C.U.M instead of using WebSocket

id love to contribute but I didn't have any experience in developing using python

**Comment by thejoabo** [comment]
Hello @gabeaventh , thanks for reaching out, I didn't even realize that they changed the bot so much. I know S.C.U.M but above all, this autobot is a learning project for me, so these solutions (such as entire libraries to handle discord's API) aren't an option. I've been really busy lately but I already have a working version using reactions, now I have to figure out how to send slash commands. 

Well, when I have more time I'll think about my own solution.  =)

**Comment by gabeaventh** [comment]
sure sure, hope soon you will have time to do your own solutions

**Comment by thejoabo** [comment]
Hey @gabeaventh , just as a quick update, I figure out how to send it ! It was pretty simple tbh (it follows the same logic as normal interactions), I'll be committing when I implement it on the current build =)

![Untitled](https://user-images.githubusercontent.com/49594896/188261675-7feec67e-283a-42b7-941a-f50efc68bb2d.png)

**Comment by gabeaventh** [comment]
nice! ill gladly waiting

**Comment by thejoabo** [comment]
Fixed at v1.2.1
