### ISSUE TITLE
Connection Lost on Mac

### ISSUE THREAD

**Issue by JedanDavis** [thejoabo/virtualfisher-bot#3]
Hey man, nice work setting up this helper. I have an issue though, i keep getting the connection lost error when i try to run it. Any idea as why that might be?

**Comment by thejoabo** [comment]
Hello @JedanDavis , connection lost is related to the websocket (used by discord's API to provide realtime data about the messages and user status), **I would need a screenshot of the error to properly troubleshoot the issue**. Can you first check if you have the proper "_websocket-client_" library installed and please assure that is exactly "_websocket-client_" and not just "_websocket_" library (they do different things).

PS: 
- If you can, please take a screenshot and send me here or in my email: dev.joabo@pm.me
- This project is no longer actively supported by me, therefore other errors may occur, feel free to report them
