### ISSUE TITLE
Question about running on mac

### ISSUE THREAD

**Issue by tmarvint** [thejoabo/virtualfisher-bot#34]
I just have a question, can this run on a MacOS or is that not possible?

**Comment by thejoabo** [comment]
@tmarvint I don't have a Mac on hand to try it, but it might work if you change the "windows-curses" module to "curses" on the requirements. 
So, before installing, download the repository folder and do the following changes to the "requirements.txt" file:

requirements.txt >>

#-------- Ess ---------#
configparser >= 5.2.0
requests >= 2.28.1
websocket-client >= 1.3.3
#windows-curses >= 2.3.0
**curses**

#-------- Env ---------#
certifi >= 2022.6.15
charset-normalizer >= 2.1.0
idna >= 3.3
urllib3 >= 1.26.10

<<

And then install & run it normally. It **should** work fine =)

**Comment by tmarvint** [comment]
> @tmarvint I don't have a Mac on hand to try it, but it might work if you change the "windows-curses" module to "curses" on the requirements. So, before installing, download the repository folder and do the following changes to the "requirements.txt" file:
> 
> requirements.txt >>
> 
> ```
> #-------- Ess ---------#
> configparser >= 5.2.0
> requests >= 2.28.1
> websocket-client >= 1.3.3
> #windows-curses >= 2.3.0
> curses
> 
> #-------- Env ---------#
> certifi >= 2022.6.15
> charset-normalizer >= 2.1.0
> idna >= 3.3
> urllib3 >= 1.26.10
> ```
> 
> <<
> 
> And then install & run it normally. It **should** work fine =)

Okay that for some reason didn't work for me and so I legit just deleted the windows-curses line and it worked perfectly

**Comment by thejoabo** [comment]
great then !!
