### ISSUE TITLE
immediately crashing after opening

### ISSUE THREAD

**Issue by segman1** [thejoabo/virtualfisher-bot#43]
DEBUG -> Exception - Response

            TRACEBACK -> [FrameInfo(frame=<frame at 0x00000182BBFF1850, file 'C:\\Users\\User\\virtualfisher-bot\\autofishbot.py', line 467, code message_receiver>, filename='C:\\Users\\User\\virtualfisher-bot\\autofishbot.py', lineno=456, function='message_receiver', code_context=['            response = session.receive_event()\n'], index=0), FrameInfo(frame=<frame at 0x00000182BC549A00, file 'C:\\Users\\User\\virtualfisher-bot\\app\\DiscordWrapper.py', line 272, code receive_event>, filename='C:\\Users\\User\\virtualfisher-bot\\app\\DiscordWrapper.py', lineno=272, function='receive_event', code_context=['        _response = self.ws.recv()\n'], index=0), FrameInfo(frame=<frame at 0x00000182BC54C400, file 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\websocket\\_core.py', line 359, code recv>, filename='C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\websocket\\_core.py', lineno=359, function='recv', code_context=['            opcode, data = self.recv_data()\n'], index=0), FrameInfo(frame=<frame at 0x00000182BC54D580, file 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\websocket\\_core.py', line 382, code recv_data>, filename='C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\websocket\\_core.py', lineno=382, function='recv_data', code_context=['        opcode, frame = self.recv_data_frame(control_frame)\n'], index=0), FrameInfo(frame=<frame at 0x00000182BC54D740, file 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\websocket\\_core.py', line 403, code recv_data_frame>, filename='C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\websocket\\_core.py', lineno=403, function='recv_data_frame', code_context=['            frame = self.recv_frame()\n'], index=0), FrameInfo(frame=<frame at 0x00000182BC549BA0, file 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\websocket\\_core.py', line 442, code recv_frame>, filename='C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\websocket\\_core.py', lineno=442, function='recv_frame', code_context=['        return self.frame_buffer.recv_frame()\n'], index=0), FrameInfo(frame=<frame at 0x00000182BBFF1620, file 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\websocket\\_abnf.py', line 360, code recv_frame>, filename='C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\websocket\\_abnf.py', lineno=338, function='recv_frame', code_context=['                self.recv_header()\n'], index=0), FrameInfo(frame=<frame at 0x00000182BC030AF0, file 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\websocket\\_abnf.py', line 294, code recv_header>, filename='C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\websocket\\_abnf.py', lineno=294, function='recv_header', code_context=['        header = self.recv_strict(2)\n'], index=0), FrameInfo(frame=<frame at 0x00000182BC547950, file 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\websocket\\_abnf.py', line 373, code recv_strict>, filename='C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\websocket\\_abnf.py', lineno=373, function='recv_strict', code_context=['            bytes_ = self.recv(min(16384, shortage))\n'], index=0), FrameInfo(frame=<frame at 0x00000182BC547B20, file 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\websocket\\_core.py', line 532, code _recv>, filename='C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\websocket\\_core.py', lineno=526, function='_recv', code_context=['            return recv(self.sock, bufsize)\n'], index=0), FrameInfo(frame=<frame at 0x00000182BC0308D0, file 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\websocket\\_socket.py', line 122, code recv>, filename='C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\websocket\\_socket.py', lineno=122, function='recv', code_context=['        raise WebSocketConnectionClosedException(\n'], index=0)]

            EVENT -> Connection to remote host was lost.

            STACK -> [FrameInfo(frame=<frame at 0x00000182BC55B230, file 'C:\\Users\\User\\virtualfisher-bot\\app\\Util.py', line 18, code debug>, filename='C:\\Users\\User\\virtualfisher-bot\\app\\Util.py', lineno=22, function='debug', code_context=['            STACK -> {stack()}\\n\n'], index=0), FrameInfo(frame=<frame at 0x00000182BBFF1850, file 'C:\\Users\\User\\virtualfisher-bot\\autofishbot.py', line 467, code message_receiver>, filename='C:\\Users\\User\\virtualfisher-bot\\autofishbot.py', lineno=467, function='message_receiver', code_context=["            debugger.debug(e, 'Exception - Response')\n"], index=0), FrameInfo(frame=<frame at 0x00000182BC554E40, file 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py', line 910, code run>, filename='C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py', lineno=910, function='run', code_context=['                self._target(*self._args, **self._kwargs)\n'], index=0), FrameInfo(frame=<frame at 0x00000182BC557440, file 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py', line 973, code _bootstrap_inner>, filename='C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py', lineno=973, function='_bootstrap_inner', code_context=['                self.run()\n'], index=0), FrameInfo(frame=<frame at 0x00000182BC554C80, file 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py', line 930, code _bootstrap>, filename='C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py', lineno=930, function='_bootstrap', code_context=['            self._bootstrap_inner()\n'], index=0)]

0 values:
sigma: (0, 0.12289)

[!] User exited.

C:\Users\User\virtualfisher-bot>

**Comment by thejoabo** [comment]
Hello, @segman1 , please read: #37 .
Try to clear your DNS cache and change your IP address.
