### ISSUE TITLE
I have been running this code and after 1 or 2 hour it gets an error !

### ISSUE THREAD

**Issue by hjbsd** [thejoabo/virtualfisher-bot#47]
![Screenshot (2)](https://user-images.githubusercontent.com/116171372/196723004-a39a9386-46d9-4ca4-877c-baea110380c3.png)

**Comment by hjbsd** [comment]
It's happening every single time ! 
Like i have to restart the code every 1-2 hour later

**Comment by thejoabo** [comment]
> I can assure you that this has something to do with your own connection, I was running 3-5 hours without errors, it just so that I got banned for a year last time without even the captcha appearing
> 
> beware, its good to turn it off every random time, and turn it on every random time they have been watching the bot pattern

Agreed, @hjbsd try to clearing DNS cache and if the problem persists, use it through a VPN/Proxy.
