### ISSUE TITLE
captcha solver wont work

### ISSUE THREAD

**Issue by spira007** [thejoabo/virtualfisher-bot#49]
it just simply doesnt work, and the whole thing just stops. do i need to make that botted channel opened always?

**Comment by thejoabo** [comment]
Hello @spira007 ,
More details are needed, **I can't figure out whats going on unless I can reproduce the error on my machine.**

Please awnser:

- Have you correctly set up your config file ? ([FAQ](https://github.com/thejoabo/virtualfisher-bot/blob/main/assets/faq.md))
- Are you using a valid API key ? ([Guide](https://github.com/thejoabo/virtualfisher-bot/blob/main/assets/faq.md#how-do-i-get-my-ocr_api_key-))
- What logs do you get when its trying to solve ? (on the top part - while running - and on terminal - after it stops)
- Does the program literally crash or just halts indefinitely ?
- Can you clarify  "_do i need to make that botted channel opened always?"_ ?
- Does it attempt to re-generate a new code by sending "_/verify regen_" ?
- Which version of python are you running and are all dependencies properly installed ? ([Guide](https://github.com/thejoabo/virtualfisher-bot#installation-and-update))
- Have you tried setting the DEBUG option to true on your config file ?

**Comment by spira007** [comment]
it didnt send verify regen, and it is probably me who pressed P outside of the menu window, but it anyways stops fishing

**Comment by spira007** [comment]
but now, it works
