### ISSUE TITLE
error when attempting to run bot

### ISSUE THREAD

**Issue by jimmymcskimmy** [thejoabo/virtualfisher-bot#52]
`DEBUG` -> Exception - Response

            TRACEBACK -> [FrameInfo(frame=<frame at 0x000001D7813E9C10, file 'autofishbot.py', line 467, code message_receiver>, filename='autofishbot.py', lineno=456, function='message_receiver', code_context=['            response = session.receive_event()\n'], index=0), FrameInfo(frame=<frame at 0x000001D7835B4040, file 'C:\\Users\\plate\\virtualfisher-bot\\app\\DiscordWrapper.py', line 272, code receive_event>, filename='C:\\Users\\plate\\virtualfisher-bot\\app\\DiscordWrapper.py', lineno=272, function='receive_event', code_context=['        _response = self.ws.recv()\n'], index=0), FrameInfo(frame=<frame at 0x000001D7835B9220, file 'C:\\Users\\plate\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\websocket\\_core.py', line 362, code recv>, filename='C:\\Users\\plate\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\websocket\\_core.py', lineno=362, function='recv', code_context=['            opcode, data = self.recv_data()\n'], index=0), FrameInfo(frame=<frame at 0x000001D7835AD740, file 'C:\\Users\\plate\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\websocket\\_core.py', line 385, code recv_data>, filename='C:\\Users\\plate\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\websocket\\_core.py', lineno=385, function='recv_data', code_context=['        opcode, frame = self.recv_data_frame(control_frame)\n'], index=0), FrameInfo(frame=<frame at 0x000001D7835AD900, file 'C:\\Users\\plate\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\websocket\\_core.py', line 406, code recv_data_frame>, filename='C:\\Users\\plate\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\websocket\\_core.py', lineno=406, function='recv_data_frame', code_context=['            frame = self.recv_frame()\n'], index=0), FrameInfo(frame=<frame at 0x000001D7835B41E0, file 'C:\\Users\\plate\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\websocket\\_core.py', line 445, code recv_frame>, filename='C:\\Users\\plate\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\websocket\\_core.py', lineno=445, function='recv_frame', code_context=['        return self.frame_buffer.recv_frame()\n'], index=0), FrameInfo(frame=<frame at 0x000001D7813EA4D0, file 'C:\\Users\\plate\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\websocket\\_abnf.py', line 360, code recv_frame>, filename='C:\\Users\\plate\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\websocket\\_abnf.py', lineno=338, function='recv_frame', code_context=['                self.recv_header()\n'], index=0), FrameInfo(frame=<frame at 0x000001D7814428E0, file 'C:\\Users\\plate\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\websocket\\_abnf.py', line 294, code recv_header>, filename='C:\\Users\\plate\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\websocket\\_abnf.py', lineno=294, function='recv_header', code_context=['        header = self.recv_strict(2)\n'], index=0), FrameInfo(frame=<frame at 0x000001D7835AE780, file 'C:\\Users\\plate\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\websocket\\_abnf.py', line 373, code recv_strict>, filename='C:\\Users\\plate\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\websocket\\_abnf.py', lineno=373, function='recv_strict', code_context=['            bytes_ = self.recv(min(16384, shortage))\n'], index=0), FrameInfo(frame=<frame at 0x000001D7835AE950, file 'C:\\Users\\plate\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\websocket\\_core.py', line 535, code _recv>, filename='C:\\Users\\plate\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\websocket\\_core.py', lineno=529, function='_recv', code_context=['            return recv(self.sock, bufsize)\n'], index=0), FrameInfo(frame=<frame at 0x000001D781441E40, file 'C:\\Users\\plate\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\websocket\\_socket.py', line 122, code recv>, filename='C:\\Users\\plate\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\websocket\\_socket.py', lineno=122, function='recv', code_context=['        raise WebSocketConnectionClosedException(\n'], index=0)]

            EVENT -> Connection to remote host was lost.

            STACK -> [FrameInfo(frame=<frame at 0x000001D7835B7230, file 'C:\\Users\\plate\\virtualfisher-bot\\app\\Util.py', line 18, code debug>, filename='C:\\Users\\plate\\virtualfisher-bot\\app\\Util.py', lineno=22, function='debug', code_context=['            STACK -> {stack()}\\n\n'], index=0), FrameInfo(frame=<frame at 0x000001D7813E9C10, file 'autofishbot.py', line 467, code message_receiver>, filename='autofishbot.py', lineno=467, function='message_receiver', code_context=["            debugger.debug(e, 'Exception - Response')\n"], index=0), FrameInfo(frame=<frame at 0x000001D7835BB040, file 'C:\\Users\\plate\\AppData\\Local\\Programs\\Python\\Python38\\lib\\threading.py', line 870, code run>, filename='C:\\Users\\plate\\AppData\\Local\\Programs\\Python\\Python38\\lib\\threading.py', lineno=870, function='run', code_context=['                self._target(*self._args, **self._kwargs)\n'], index=0), FrameInfo(frame=<frame at 0x000001D7835B2440, file 'C:\\Users\\plate\\AppData\\Local\\Programs\\Python\\Python38\\lib\\threading.py', line 932, code _bootstrap_inner>, filename='C:\\Users\\plate\\AppData\\Local\\Programs\\Python\\Python38\\lib\\threading.py', lineno=932, function='_bootstrap_inner', code_context=['                self.run()\n'], index=0), FrameInfo(frame=<frame at 0x000001D7835B6E40, file 'C:\\Users\\plate\\AppData\\Local\\Programs\\Python\\Python38\\lib\\threading.py', line 890, code _bootstrap>, filename='C:\\Users\\plate\\AppData\\Local\\Programs\\Python\\Python38\\lib\\threading.py', lineno=890, function='_bootstrap', code_context=['            self._bootstrap_inner()\n'], index=0)]`

0 values:
sigma: (0, 0.12289)

[!] User exited.

**Comment by jimmymcskimmy** [comment]
looked at #43 and the solutions there didn't work

**Comment by thejoabo** [comment]
Hey @jimmymcskimmy , 

- have you tried running it on Python 3.10 (or above) ? I saw that you are using 3.8, which I did not perform any tests. 
- did you installed the dependencies (with the specified versions in the requirements) ? 
- have you been able to run the bot at least once (without errors) ?

Other than that, there is not much else to be said, if your token is correctly setup on the config file, your connection is been refused for some reason, this issue seems to go away at random. I'm currently working on the new version, which may solve these kind of errors.

**Comment by jimmymcskimmy** [comment]
just installed 3.11 still having the same error, I have not been able to run the bot at least once without errors. I believe I have all the requirements the versions may be slightly higher I might try getting my token again to see if there was an issue

**Comment by jimmymcskimmy** [comment]
fixed supposedly my token was incorrect, thanks for the help!
