### ISSUE TITLE
Level incorrectly shown

### ISSUE THREAD

**Issue by yudhistiraindyka** [thejoabo/virtualfisher-bot#8]
The demo shown in the page shows the correct one

![image](https://user-images.githubusercontent.com/33085123/180377286-ef669f3a-fcdd-48ce-8216-104f2e599512.png)

**Comment by thejoabo** [comment]
Hello @yudhistiraindyka 

That seems pretty weird, but I think i know whats going on. Can you send a screenshot of your inventory on Discord ? [(use _%inv_)](https://prnt.sc/Roe8E3oz_FHw)

**Comment by yudhistiraindyka** [comment]
I think it's got something to do with how the regex for the level works, since maybe you forgot to account for prestige levels

![image](https://user-images.githubusercontent.com/33085123/180484009-3bb6233c-238b-43b3-8c76-ab9ba98ddd3f.png)

**Comment by thejoabo** [comment]
Ohh, I didn't even know about the prestige. The regex excludes everything but numbers and symbols. My concern is that I'm currently filtering the level searching every line for a match to "_level_", those patterns "_:<:\__" stands for an emote, so my theory was that somewhere else had "_level_"within the line. 
Anyway, **I'll release a update later today** to fix some issues (including that one you posted early about the screen, I added a function to check the size). I'll try to work around the text scraping issues.

Thanks for reporting. **If the problem persists after the update feel free to reopen this issue again** so I can guide you to a more detailed troubleshoot.
